apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # Prometheus serves at /prometheus/ path (--web.route-prefix)
    url: http://localhost:9090/prometheus
    isDefault: true
    editable: false
